version: '3'

services:
  rps:
    build:
      context: .
    command: ./wait-for.sh postgres:5432 -- npm start
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      ./.env
    networks:
      - rps
    restart: always
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - rps
    networks:
      - rps
  postgres:
    image: postgres:14-alpine3.15
    ports:
      - '5432:5432'
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    networks:
      - rps
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - rps

volumes:
  pgadmin-data:

networks:
  rps:
    driver: bridge