name: CD
on: [push]
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "SECTRETS    ${{ secrets.SSH_KEY }} STAGING_SSH_KEY."
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$SSH_KEY" > ~/.ssh/staging.key
#          chmod 600 ~/.ssh/staging.key
#          cat >>~/.ssh/config <<END
#          Host staging
#            HostName $SSH_HOST
#            User $SSH_USER
#            IdentityFile ~/.ssh/staging.key
#            StrictHostKeyChecking no
#          END
#        env:
#          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
#          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
#          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}